### ISSUE TITLE
Get functional tests working and fix access issues

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/entityform#10]
Currently the main problem seems to be entity_access. Need to dig a little deeper with a fresher mind.

```
257 passes, 7 fails, 0 exceptions, and 86 debug messages.
```

Seems a workable state.

**Comment by argiepiano** [comment]
I suggest using `entity_plus_access()` which makes use of `access callback` in the entity info definition. Backdrop's core `entity_access` does not, which often creates problems.
