### ISSUE TITLE
Cron runs trigger EntityMalformedException - caused by leftover data after deleting entityform_types via UI

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/entityform#14]
Whenever cron runs:
```
EntityMalformedException: Missing bundle property on entity of type entityform. in entity_extract_ids() (line 460 of /var/www/porting/html/core/modules/entity/entity.module).
```

Steps to reproduce:

1. Create an entityform_type
2. Attach a new field (do not reuse)
3. Create some instances of entityform based on that type
4. Eventually delete one of those instances
5. Delete the type - without deleting all instances
6. Run cron

This is caused by field_purge_batch() in field_cron(). It tries to clean up field instance data, but that fails, if the entity type - in this case entityform_type instances (aka the bundle) don't exist anymore.

The actual problem is, that the create() method sometimes returns NULL instead of an instance of Entityform.

**Comment by argiepiano** [comment]
The changes in #15 seem to have fixed this as well - unless I'm missing a step to reproduce.

**Comment by indigoxela** [comment]
> The changes in https://github.com/backdrop-contrib/entityform/issues/15 seem to have fixed this as well

Not for me, though. the EntityMalformedException persists when running cron - even with the patch applied.

I do have an idea, what might be causing this. But I think, removing the non-existent 'label callback' is a step forward.

**Comment by indigoxela** [comment]
The explanation for this is quite simple:

This is caused by field_purge_batch() in field_cron().

It tries to clean up field instance data, but that fails, if the entity type - in this case `entityform_type` instances don't exist anymore.

Base problem: when deleting entityform *types* via UI, the corresponding entities won't get cleaned up. Neither will the fields get cleaned up. There are zombie rows in table entityform and zombie field tables, which we can't get rid of, as the field cleanup job needs the entity info for that. But the entity type is gone.

Does this sound familiar @argiepiano? :wink:

**Comment by argiepiano** [comment]
OK, I'll take a closer look at this tonight again. I will look at each of the steps to be sure I can reproduce this.

**Comment by indigoxela** [comment]
This is as close as I can get: #19 This still doesn't prevent the EntityMalformedExceptions on cron runs, whenever field_purge_batch() attempts to clean up fields, but prevents all sorts of php errors (fatal errors) with entityforms with missing (deleted) entityform_types.

**Comment by indigoxela** [comment]
Reopening, as there's no solution, yet for the EntityMalformedException - the main topic here.
