### ISSUE TITLE
Delete confirmation form seems incomplete

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entityform#17]
<img width="954" alt="Screen Shot 2024-10-18 at 9 37 09 PM" src="https://github.com/user-attachments/assets/1d664139-2abc-462f-bc01-fac6f75666bf">

This is also an issue in D7, BTW.

**Comment by indigoxela** [comment]
> This is also an issue in D7, BTW.

Yes, this looks exactly the same in D7 - which makes this issue low prio for me. But still something to fix later.
Many thanks for spotting and reporting. :+1:

**Comment by indigoxela** [comment]
> ... still something to fix later.

Or maybe now. I'm grateful for any simple problem, which this one is. :wink:
