### ISSUE TITLE
Not possible to delete entityform types

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/entityform#7]
Go to admin/structure/entityform_types, click on a delete link, get a confirm page, get back to the overview and the type still exists. :-1: No warnings or errors, just silently ignored.

There's even a log message "Deleted Entityform Type blablabla". :thinking: 

Possibly has to do with the static cache in EntityPlusController::load ... We get an empty array at first.

EDIT: After quite some forward and back it turned out, that the problem was an inconsistency in "entity keys" for "id".
This might be fixed by https://github.com/backdrop-contrib/entityform/commit/59a4f97065ef030f3d8976269bcb87f2df9e2b8e (reverted to stick with same key as used in Drupal version)

EDIT 2: Final fix is https://github.com/backdrop-contrib/entityform/commit/6325ec67f26499efbba05de2ab6924f8872042a4

**Comment by indigoxela** [comment]
Hm... could be related to https://github.com/backdrop/backdrop-issues/issues/5440
Not sure, yet.

**Comment by indigoxela** [comment]
Wow, found the problem. Has nothing to do with caching. And can't solve it. :disappointed:

**Comment by argiepiano** [comment]
Is this a problem in the d7 version too?  Or is it an Entity ui issue?

**Comment by indigoxela** [comment]
> Is this a problem in the d7 

No, not a problem in D7.

I think, I fixed it now, but wonder, if that solution's smart. Maybe a little pause to think it over... :wink: 

And, hey, thank you so much for chiming in here @argiepiano. :pray:  I never did anything with entity_plus so far and entityform's quite complex, too.
